name: Deploy GitHub Pages (multi-app)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies (PNPM)
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install

      # Build web (Vue)
      - name: Build web app
        run:  pnpm --filter web run docs:build

      # Build web (Vue)
      - name: Build web new-app
        run:  pnpm --filter new-app run docs:build

      # Copy outputs into one dist folder
      - name: Prepare deploy folder
        run: |
          mkdir dist
          cp -r apps/new-app/dist dist/new-app
          cp -r docs/.vitepress/dist dist/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
