name: Deploy GitHub Pages (multi-app)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # PNPM & Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies (PNPM)
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install

      # ---------- Build 단계 ----------
      # Build test (Vue)
      - name: Build test app
        run:  pnpm --filter test run build

      # Build web (Vue)
      - name: Build new-app app
        run:  pnpm --filter new-app run build

      # Build storybook
      - name: Build storybook app
        run:  pnpm --filter @repo/ui build-storybook

      # ---------- 합본 ----------
      # Copy outputs into one dist folder
      - name: Compose gh-pages folder
        run: |
          rm -rf dist
          mkdir -p dist/test
          mkdir -p dist/new-app
          mkdir -p dist/storybook
          cp -r apps/test/dist/* dist/test
          cp -r apps/new-app/dist/* dist/new-app
          cp -r packages/ui/storybook-static/* dist/storybook

      # ---------- GitHub Pages 배포 ----------
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
